export const TIMELINE = {
    "1949": ["Ngày 20/8/1949, tại Vườn Bách Thú Hà Nội, Thiếu đoàn Bạch Đằng được thành lập do Trưởng Trần Trung Du làm Thiếu Trưởng."],
    "1950": ["Tháng 2/1950 nhằm 23 tháng Chạp năm Kỷ Sửu, Tráng đoàn Bạch Đằng được thành lập với hai toán.", "Tháng 9/1950, Đạo Đồng Nhân thành lập do Trưởng Trần Trung Du làm Đạo Trưởng."],
    "1954": ["Trưởng Trần Trung Du cùng gia đình chuyển vào Nam, Trưởng Du cùng một số Tráng sinh cũ đã thành lập Tráng đoàn tại Sài Gòn."],
    "1960": ["Lễ ra mắt Tráng đoàn Bạch Đằng được tổ chức tại rạp hát Thống Nhất.", "Liên đoàn Bạch Đằng bao gồm Bầy Bạch Đằng, Thiếu đoàn Bạch Đằng, Tráng đoàn Bạch Đằng được sự chấp thuận của Bộ Tổng Ủy viên, Liên đoàn Bạch Đằng sát nhập vào Đạo Hoa Lư."],
    "1975": ["Bạch Đằng gián đoạn sinh hoạt."],
    "1991": ["Thành lập các Toán Tráng: Chương Dương, Sông Hát, Vân Đồn, Mê Linh, Hàm Tử, Tây Kết."],
    "1992": ["Ngày 28/1/1992, Bạch Đằng phục hoạt."],
    // "1993": ["Các Bầy và Thiếu đoàn bắt đầu được hình thành, chị Trần Thị Diệu Quỳnh đảm trách việc hướng dẫn các Sói Già, chị Trần Thị Ngọc Nga phụ trách về Ngành Nữ, anh Trần Minh Thiện phụ trách về Ngành Thiếu."],
    "1994": ["Từ ngày 29/4 - 1/5/1994, Trại hè Đồng Phú là kì trại đầu tiên của toàn Liên đoàn Bạch Đằng với đầy đủ các ngành Ấu, Thiếu, Tráng."],
    "1997": ["Tháng 6/1997, thành lập Kha đoàn Bạch Đằng do anh Đỗ Hữu Đức làm Kha Trưởng.", "Mùa hè năm 1997, hình thành nhóm Phụ huynh bảo trợ, tiền thân của Ban Bảo Trợ Đạo Bạch Đằng."],
    "2000": ["Ngày 9/1/2000, chính thức thành lập Liên đoàn Bạch Đằng do anh Trần Minh Thiện làm Liên đoàn Trưởng."],
    "2005": ["Đầu năm 2005, thành lập Thiếu đoàn Nữ Bạch Đằng do chị Trần Thị Diệu Quỳnh làm Thiếu Trường.", "Ngày 7/8/2005, thành lập Ấu đoàn Nữ Bạch Đằng do chị Nguyễn Thị Hoàng Oanh làm Akela."],
    "2006": ["Ngày 15/1/2006, thành lập Liên đoàn Nữ Bạch Đằng do chị Trần Thị Diệu Quỳnh làm Liên đoàn Trưởng.", "Ngày 3/12/2006, Kha đoàn Nữ Bạch Đằng chính thức được thành lập do chị Nguyễn Thị Hoàng Oanh làm Kha Trưởng"],
    "2008": ["Ngày 6/1/2008, ra mắt Liên đoàn Vân Cừ do anh Võ Quang Nguyên Phổ làm Liên đoàn Trường.", "Ngày 27/1/2008, ra mắt Đạo Bạch Đằng do anh Trần Minh Thiện làm Đạo Trưởng."],
    "2010": ["Ngày 3/10/2010, thành lập Bầy Lục Nam, thuộc Liên đoàn Vân Cừ, do anh Nguyễn Minh Tuấn làm Akela."],
    "2011": ["Ngày 8/5/2011, thành lập Bầy Thủy Nguyên, thuộc Liên đoàn Nữ Bạch Đằng, do chị Nguyễn Nhật Quỳnh Trang làm Akela."],
    "2019": ["Tháng 7/2019, thành lập Kha đoàn Vân Cừ, thuộc Liên Đoàn Vân Cừ, do anh Nguyễn Phạm Duy Nhân làm Kha Trưởng."],
    "Hiện Tại": [""]
}